// section.h
// Spontz Demogroup

#ifndef SECTION_H
#define SECTION_H
#include <string>
using namespace std;

#define SECTION_PARAMS		32
#define SECTION_STRINGS		32
#define SECTION_SPLINES		32
#define SECTION_MODIFIERS	32

typedef struct {
	int spline;
	int param;
	int mode;
} Modifier;

class Section {
public:
	int			type;
	// section data
	string		identifier;							// Unique section identifier generated by the demo editor
	string		DataSource;							// origin of this section (for error messages)
	//int			staticSectionIndex;					// index to static section (to get generic functions)
	float		startTime;							// section start time
	float		endTime;							// section end time
	float		duration;							// total section seconds
	int			layer;								// layer where sections run (priority)
	int			enabled;							// 1: Section enabled; 0: Section disabled
	int			loaded;								// 1: Section loaded; 0: Section not loaded
	float		runTime;							// seconds elapsed since section start
	int			hasBlend;							// has blending function parameters?
	int			sfactor;							// default source blending factor
	int			dfactor;							// default dest blending factor
	int			hasAlpha;							// has alpha function parameters?
	int			alphaFunc;							// alpha function
	float		alpha1;								// alpha reference value (hack: no se sabe bien que es esto), renombrar estas variables y documentar aqui
	float		alpha2;								// alpha reference value (hack: no se sabe bien que es esto), renombrar estas variables y documentar aqui
	int			paramNum;							// number of parameters
	float		param[SECTION_PARAMS];				// float parameters
	int			stringNum;							// number of strings
	string		strings[SECTION_STRINGS];			// string parameters
	int			splineNum;							// number of splines
	// TODO: Add splines support
	//Motion*		splines[SECTION_SPLINES];			// spline pointers
	string		splineFiles[SECTION_SPLINES];		// spline file names
	float		splineDuration[SECTION_SPLINES];	// spline duration in seconds
	void*		vars;								// pointer to section local variables


	// Members
	Section();
	virtual ~Section() {};

	// ******************************************************************

	virtual void preload()	{};	// load static data from disk
	virtual void load()		{};	// load parametrized data from disk
	virtual void init()		{};	// set up local variables before execution
	virtual void exec()		{};	// render a new frame
	virtual void end ()		{};	// destroy allocated memory
			
private:
	
};

#endif